bind = SUPER, F2, exec, ~/.local/scripts/spotify-scratchpad.sh # Open Spotify in scratchpad. Also you can open any other app with this
bind = Super, A, exec, ~/.local/scripts/toggle_mousepad.sh # Open mousepad as sidebar
bind = Super+Shift, E, exec, hyprctl dispatch exec "[float; size 960 540; move 480 270; opacity 0.95 0.8] xdg-open ./"
